### ISSUE TITLE
Territory subdivision

### ISSUE THREAD

**Issue by rotsee** [papandreou/node-cldr#81]
I'd like to try and add territory subdivisions (`dk85` => “Sjælland”), but I wonder what's the best way to do it.

Should it be a new method like `extractSubdivisionDisplayNames(locale=root)`?
```
> cldr.extractSubdivisionDisplayNames('en').dk85;
'Zealand'
```

Or should subdivisions be returned by `extractTerritoryDisplayNames()`?

**Comment by papandreou** [comment]
That sounds like a great idea!

I think I lean towards `extractSubdivisionDisplayNames` because it's more 1-to-1 with the CLDR data, and similar to how [`extractTerritoryContainmentGroups`](https://github.com/papandreou/node-cldr/blob/c828319ee6e2b4a6508e348308c8dd0e35ceca4e/lib/cldr.js#L1711) is also separate (whoops, that one isn't listed in README).

I can see that in some ways it would be more ergonomic to get the subdivision display names mixed into some kind of structure with the territory display names. I think the right thing would be to keep this module low level and then publish another package the more "opinionated" representation, which could then be generated at publish time using `cldr` as a dev dep. I made a module for rendering translated lists of items along those lines: https://github.com/papandreou/this-and-that

**Comment by rotsee** [comment]
I agree about keeping it in line with CLDR data (I use this lib in a similar fashion, to power more high-level libraries). `extractSubdivisionDisplayNames` it is!

**Comment by papandreou** [comment]
For completeness I guess we should also make an extractor for the subdivision _containment_ data: https://github.com/papandreou/node-cldr/blob/master/3rdparty/cldr/common/supplemental/subdivisions.xml

(Didn't notice that until now just, but apparently it was added back in CLDR 28 :sweat_smile:)

Then `extractTerritoryContainmentGroups` + `extractTerritoryDisplayNames` would be symmetrical to that + `extractSubdivisionDisplayNames` :sunglasses:

> similar to how `extractTerritoryContainmentGroups` is also separate (whoops, that one isn't listed in README).

Added quick docs for that here: https://github.com/papandreou/node-cldr#extractterritorycontainmentgroups

Might be good to add links to/from those sections. It might not be totally obvious to everyone that "territories" are at the continent/subcontinent/country level, whereas "subdivisions" is everything further down. If that's even the exact definition.
